### ISSUE TITLE
subnet or iterate functions don't work

### ISSUE THREAD

**Issue by jtarashuck-hcs** [daniellawrence/aws-map#11]
I'm not sure if I'm using the correct syntax or if something else is wrong. I can get this tool to work when using --vpc vpc-id but as suggested in the readme, my VPC is far too large and I'd like to break it down into subnets. I get the following error when trying to use the subnet feature as well as the iterate feature:

./mapall.py --region us-east-1 --subnet subnet-401c7b09
digraph G {
overlap=false
ranksep=1.6
splines=ortho
Traceback (most recent call last):
  File "./mapall.py", line 1435, in <module>
    main()
  File "./mapall.py", line 1431, in main
    generate_map(args.output, args)
  File "./mapall.py", line 1398, in generate_map
    obj.draw(fh)
  File "./mapall.py", line 328, in draw
    if not self.inVpc(self.args.vpc) or not self.inSubnet(self.args.subnet):
  File "./mapall.py", line 304, in inSubnet
    if subnet and self['SubnetId'] != subnet:
  File "./mapall.py", line 85, in __getitem__
    return self.data.get(key, None)
AttributeError: 'Instance' object has no attribute 'get'

**Comment by fredcooke** [comment]
I also get the above, and the `--iterate vpc` fails with a different issue for me, but possibly because of a `VPC` with **nothing** connected to it, at a guess (didn't check, just speculating). Output here:

```
fred$ ./mapall.py --region ap-southeast-2 --iterate vpc
Traceback (most recent call last):
  File "./mapall.py", line 1449, in <module>
    main()
  File "./mapall.py", line 1442, in main
    generate_map(f, args)
  File "./mapall.py", line 1412, in generate_map
    obj.draw(fh)
  File "./mapall.py", line 1058, in draw
    if self.inVpc(self.args.vpc) and self.inSubnet(self.args.subnet):
  File "./mapall.py", line 1073, in inVpc
    for subnet in subnets.split(','):
AttributeError: 'NoneType' object has no attribute 'split'
```
